export const todos = [
  '6-12',
  '12-18',
  '18-24',
  
  'small projects',
  'big projects',
  'java or js algo and ds',
  'exercise',
  'relax and health',
  'rental management',
  'investment/trading',
  
  'social/talk to someone',
  
  'dom',
  'pure js',
  'small react',
  
  'big react',
  'system design',
  'mern',
  'work',
  'springboot',
  'sre',
  'firebase',
  'next.js',
  'big browser pure js',
  'ai',
  'pwa',
  'ojet',
  'coding tools',
  'graphql',
  'cms',
  'react native',
  
  'dfs',
  'bfs',
  'dp',
  'one other topic',
  
  'peloton',
  'hiking or long walk with podcast',
  'rope jump',
  'fitness 19',
  'running track at hillsdale high school',
  'pickleball/badminton/tennis',
  'abs',
  'climbing laurelwoods park',
  'solo tennis',
  'swim',
  
  'sunshine 晒背 or sit outside',
  'short walk with podcast',
  'eat good/lemon water',
  'sleep/up early',
  'no mass',
  'maintain good bp',
  'dance bachata/tango/waltz',
  'movie',
  'do gardening work/wildflower',
  'do house cleaning/organizing/trimming',
  
  'my own property',
  'cohost property',
  
  'sdt news',
  'ron walker',
  'mtm',
  'meetkevin',
  'silva',
  'mike',
  'llp news',
  'other news',
  
  'by jake',
  'give and grow',
  'twmn and ctv',
  'adt training',
  'smb training',
  'invest with henry',
  'projectfinance',
  'guillermo',
  'llp',
  'udemy',
  'other strategies',
  
  'khanacademy',
  'econ crash course',
  
  'wysertrade',
  'sdt training',
  'fractal flow',
  'other ta',
  
  'actual trading'
];
